version: 2
jobs:
  build:
    working_directory: ~/engaging-computing/rSENSE
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    # When we update ruby version we can use a dedicated image https://hub.docker.com/r/circleci/ruby/tags/
    # For now we use a general Ubuntu image with rvm
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    #  command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run:
        working_directory: ~/engaging-computing/rSENSE
        command: rm -f engaging-computing/rSENSE/.rvmrc; echo 2.3.0 > engaging-computing/rSENSE/.ruby-version; rvm use 2.3.0 --default
    # dependencies: pre:
    - run: sudo apt-get update; sudo apt-get install libreoffice libreoffice-calc unoconv
    - run: sudo apt-get install ruby-railties-4.0 bundler
    - run: sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
    - run: sudo apt-get install xvfb
    - run: gem install bundler -v 2.3.26
    - restore_cache:
        key: v1-{{checksum "Gemfile.lock" }}
    - run: bundle install --path vendor/bundle
    - save_cache:
        key: v1-{{checksum "Gemfile.lock" }}
        paths: "vendor/bundle"
    - run: bundle exec rake assets:precompile
    - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
    # database: override:
    - run: bundle exec rake db:preprep
    - run: RAILS_ENV=test bundle exec rake db:migrate --trace
    - run: bundle exec rake db:test:prepare
    # Test
    - run: xvfb-run -a bundle exec rake
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
