#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'
end

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

if ENV['RAILS_ENV'] == 'test'
  SimpleCov.command_name "Parallel" + (ENV['TEST_ENV_NUMBER'] || '')
  $LOAD_PATH.unshift(Pathname.new(APP_PATH).join('../../lib'))
  require 'simplecov_rsense'
  SimpleCov.start 'rsense'
end

require 'rails/commands'
